### ISSUE TITLE
Add server-commands to help

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyblockMod#5]
Server-commands can be retrieved via `/api/mod/commands` more information available on https://sky-commands.coflnet.com/api 

Note that `sky-commands` will replace `sky.coflnet.com` at some point

**Comment by ToruiDev** [comment]
Please Review

**Comment by Ekwav** [comment]
Does not work,
Exception log:
```
[18:41:50] [Client thread/INFO]: [de.torui.coflsky.CoflSkyCommand:func_71515_b:54]: []
[18:41:50] [Client thread/INFO]: [CHAT] Available local sub-commands:
start: starts a new connection
stop: stops the connection
status: Emits status information
Server-Only Commands:
[18:41:50] [Client thread/INFO]: [de.torui.coflsky.QueryServerCommands:GetRequest:66]: Get request
[18:41:50] [Client thread/INFO]: [de.torui.coflsky.QueryServerCommands:GetRequest:85]: InputStream
[18:41:51] [Client thread/INFO]: [de.torui.coflsky.QueryServerCommands:GetRequest:95]: Result= [{"subCommand":"test","description":"Returns a test response"}]
[18:41:51] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at de.torui.coflsky.QueryServerCommands.QueryCommands(QueryServerCommands.java:26)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at de.torui.coflsky.CoflSkyCommand.ListHelp(CoflSkyCommand.java:124)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at de.torui.coflsky.CoflSkyCommand.func_71515_b(CoflSkyCommand.java:93)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:72)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:446)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:437)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java:111)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:41:51] [Client thread/INFO]: [net.minecraftforge.client.ClientCommandHandler:func_71556_a:91]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:41:57] [pool-9-thread-2/INFO]: [io.github.moulberry.notenoughupdates.auction.APIManager:lambda$updatePageTick$5:394]: Error downloading auction from Moulberry's jank API. :(
[18:42:02] [ReadingThread/INFO]: [de.torui.coflsky.websocket.WSClient:onTextMessage:107]: Received: {"type":"writeToChat","data":"{\"text\":\"\\nFLIP: �6[Lvl 1] Ammonite �2999,998 -> 1,400,000 �g[BUY]\",\"onClick\":\"/viewauction 3275fa61bde44c3892e346167eb84940\",\"hover\":\"?Candy Used 0\"}"}
[18:42:02] [ReadingThread/INFO]: [de.torui.coflsky.WSCommandHandler:HandleCommand:29]: Handling Command=Command [Type=WriteToChat, data={"text":"\nFLIP: �6[Lvl 1] Ammonite �2999,998 -> 1,400,000 �g[BUY]","onClick":"/viewauction 3275fa61bde44c3892e346167eb84940","hover":"?Candy Used 0"}]
[18:42:02] [ReadingThread/INFO]: [CHAT] 
FLIP: �6[Lvl 1] Ammonite �2999,998 -> 1,400,000 �g[BUY]
[18:42:05] [Client thread/INFO]: [de.torui.coflsky.CoflSkyCommand:func_71515_b:54]: [stop]
[18:42:05] [Client thread/INFO]: [de.torui.coflsky.websocket.WSClient:stop:76]: Closing Socket
[18:42:05] [Client thread/INFO]: [de.torui.coflsky.websocket.WSClient:stop:90]: Socket closed
[18:42:05] [Client thread/INFO]: [CHAT] you stopped the connection to Coflnet.
    To reconnect enter "/cofl start" or click this message
```

**Comment by ToruiDev** [comment]
Should be fixed now
![grafik](https://user-images.githubusercontent.com/44932079/135766674-00fbd33c-14c4-48b5-8b74-219b1390a61e.png)

**Comment by Ekwav** [comment]
LGTM!
